version: '3.5'
services:
  zbxtimedb:
    image: timescale/timescaledb-ha:pg15.4-ts2.12.0
    container_name: zbxtimedb2.12-pg15
    restart: on-failure:3
    env_file:
      - ./env_vars/env_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db/data:/var/lib/postgresql:rw
    secrets:
      - db_user
      - db_password                         
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 5s
    networks:
      - zbx
#  zbxelastic:
#    image: elasticsearch:7.17.15
#    container_name: zbxelasticdb7.17.15
#    restart: on-failure:3
#    environment:
#      - cluster.name=zabbix-elastic
#      - node.name=zbxelastic:9200
#      - cluster.initial_master_nodes=zbxelastic:9200
#      - transport.host=0.0.0.0
#      - ingest.geoip.downloader.enabled=false
#    volumes:
#      - ./els:/usr/share/elasticsearch/data
#    healthcheck:
#      test: ["CMD", "sh", "-c", "ps aux | grep elastic || exit 1"]
#      interval: 20s
#      timeout: 10s
#      retries: 2
#    networks:
#      - zbx
  zbxserver:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest #alpine-trunk Install Zabbix Alpha version
    container_name: zbxserver-pgsql
    restart: on-failure:3
    ports:
      - "10051:10051"
    env_file:
      - ./env_vars/env_zbxsrv
      - ./env_vars/env_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/var/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:rw
      - ./config/var/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:rw
      - ./config/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:rw
      - ./config/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./config/var/lib/zabbix/modules:/var/lib/zabbix/modules:rw
      - ./config/var/lib/zabbix/enc:/var/lib/zabbix/enc:rw
      - ./config/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:rw
      - ./config/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:rw
      - ./config/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
   #   - ./config/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
   #   - ./config/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
   #   - ./config/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
    secrets:
      - db_user
      - db_password 
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep zabbix_server || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 5s
    mem_limit: 1024m
    mem_reservation: 512m
    networks:
      - zbx
    depends_on:
      zbxtimedb:
        condition: service_healthy
#      zbxelastic:
#        condition: service_healthy
  zbxweb:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zbxweb-nginx
    restart: on-failure:3
    ports:
      - "80:8080"
      - "443:8443"
    env_file:
      - ./env_vars/env_db
      - ./env_vars/env_web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/etc/ssl/nginx:/etc/ssl/nginx:rw
      - ./config/usr/share/zabbix/modules/:/usr/share/zabbix/modules:rw
    #   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
    #   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
    #   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
    secrets:
      - db_user
      - db_password
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep php-fpm || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 5s
    mem_limit: 1024m
    mem_reservation: 512m
    networks:
      - zbx
    depends_on:
      zbxserver:
        condition: service_healthy
      zbxtimedb:
        condition: service_healthy
#      zbxelastic:
#        condition: service_healthy
#  zbxagent2:
#    image: zabbix/zabbix-agent2:alpine-6.4-latest
#    container_name: zbxagent2
#    restart: on-failure:3
#    ports:
#      - "10050:10050"
#    env_file:
#      - ./env_vars/env_agent2
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./config/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:rw
#      - ./config/var/lib/zabbix/modules:/var/lib/zabbix/modules:rw
#      - ./config/var/lib/zabbix/enc:/var/lib/zabbix/enc:rw
#      - ./config/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:rw
#    privileged: true
#    pid: "host"
#    stop_grace_period: 5s
#    healthcheck:
#      test: ["CMD", "sh", "-c", "ps aux | grep zabbix_agent2 || exit 1"]
#      interval: 20s
#      timeout: 10s
#      retries: 2
#      start_period: 5s
#    mem_limit: 128m
#    mem_reservation: 64m
#    networks:
#      - zbx
  zbxjava:
    image: zabbix/zabbix-java-gateway:alpine-6.4-latest
    container_name: zbxjava
    restart: on-failure:3
    ports:
      - "10052:10052"
    env_file:
      - ./env_vars/env_java
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep zabbix_java_gateway || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 5s
    mem_limit: 512m
    mem_reservation: 256m
    networks:
      - zbx
  zbxsnmp:
    image: zabbix/zabbix-snmptraps:alpine-6.4-latest
    container_name: zbxsnmp
    restart: on-failure:3
    ports:
      - "162:8162/udp"
    env_file:
      - ./env_vars/env_snmp
    volumes:
      - ./config/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:rw
      - ./config/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep snmptrapd || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 5s
    mem_limit: 256m
    mem_reservation: 128m
    networks:
      - zbx
  zbxwebservice:
    image: zabbix/zabbix-web-service:alpine-6.4-latest
    container_name: zbxwebservice
    restart: on-failure:3
    ports:
      - "10053:10053"
    env_file:
      - ./env_vars/env_webservice
    volumes:
      - ./config/var/lib/zabbix/enc:/var/lib/zabbix/enc:rw
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep zabbix_web_service || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 5s
    mem_limit: 512m
    mem_reservation: 256m
    networks:
      - zbx
#  nginx:
#    image: jc21/nginx-proxy-manager:latest
#    container_name: nginx-proxy
#    restart: on-failure:3
#    ports:
#      - "80:80"
#      - "443:443"
#      - "3005:81" # Admin Web Port
#    environment:
#      DISABLE_IPV6: 'true'
#      X_FRAME_OPTIONS: "sameorigin"
#    volumes:
#      - ./nginx/data:/data:rw
#      - ./nginx/letsencrypt:/etc/letsencrypt:rw
#    healthcheck:
#      test: ["CMD", "/bin/check-health"]
#     interval: 20s
#     timeout: 10s
#      retries: 2
#      start_period: 5s
#    networks:
#      - zbx
#    mem_limit: 512m
#    mem_reservation: 256m
volumes:
  els: {}
networks:
  zbx:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
    name: zbx
secrets:
  db_user:
    file: ./env_vars/.db_user
  db_password:
    file: ./env_vars/.db_password
#@github.com/sergeybezlepkin
