version: '3.7'
services:
  kibana:
    image: kibana:7.17.21
    container_name: zbxkibana7.17.21
    restart: always    
    ports:
       - "35601:5601"
    env_file:
       - ./env_kibana
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep kibana || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 5s
    networks:
      - zbx
networks:
  zbx:
    external: true
